#ifndef COLORS_H
#define COLORS_H
#include <efi.h>

extern EFI_GRAPHICS_OUTPUT_BLT_PIXEL GREEN;
extern EFI_GRAPHICS_OUTPUT_BLT_PIXEL WHITE;
extern EFI_GRAPHICS_OUTPUT_BLT_PIXEL BLACK;
extern EFI_GRAPHICS_OUTPUT_BLT_PIXEL YELLOW;
extern EFI_GRAPHICS_OUTPUT_BLT_PIXEL GRAY;
extern EFI_GRAPHICS_OUTPUT_BLT_PIXEL LIGHT_GRAY;
extern EFI_GRAPHICS_OUTPUT_BLT_PIXEL DARK_GRAY;
extern EFI_GRAPHICS_OUTPUT_BLT_PIXEL RED;
#endif
